# Generated by Django 4.0.6 on 2022-08-01 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_groupcustom_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcustom',
            name='day',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
