# Generated by Django 4.0.6 on 2022-08-01 06:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_alter_groupcustom_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcustom',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 1, 6, 25, 27, 436628, tzinfo=utc)),
        ),
    ]
