# Generated by Django 4.0.6 on 2022-08-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_alter_groupcustom_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcustom',
            name='day',
        ),
        migrations.AddField(
            model_name='groupcustom',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
