# Generated by Django 4.0.6 on 2022-08-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_remove_groupcustom_day_groupcustom_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcustom',
            name='create',
        ),
        migrations.RemoveField(
            model_name='groupcustom',
            name='owner',
        ),
    ]
