# Generated by Django 4.0.6 on 2022-08-01 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0007_remove_groupcustom_create_remove_groupcustom_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcustom',
            name='owner',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
